/**
 * Andryx Hourglass — Sprite procedurali pixel-art (DS-style 32x32).
 *
 * Tutti gli sprite sono OffscreenCanvas / HTMLCanvas costruiti una sola
 * volta al primo accesso (lazy). Disegnati con primitive Canvas2D semplici
 * (rect, ellipse) per restare leggeri.
 */
import { C } from './palette.js';

const cache = new Map();

function makeCanvas(w, h) {
  if (typeof OffscreenCanvas !== 'undefined') return new OffscreenCanvas(w, h);
  const c = document.createElement('canvas');
  c.width = w; c.height = h;
  return c;
}

/* Disegna `pixels` come stringa multilinea. Ogni char = 1 pixel.
   Mappa: char → colore (CSS). Spazio = trasparente. */
function drawPixelArt(pixels, palette, scale = 1) {
  const rows = pixels.trim().split('\n').map(r => r);
  const h = rows.length;
  const w = Math.max(...rows.map(r => r.length));
  const cv = makeCanvas(w * scale, h * scale);
  const ctx = cv.getContext('2d');
  ctx.imageSmoothingEnabled = false;
  for (let y = 0; y < h; y++) {
    const row = rows[y];
    for (let x = 0; x < row.length; x++) {
      const ch = row[x];
      const col = palette[ch];
      if (col) {
        ctx.fillStyle = col;
        ctx.fillRect(x * scale, y * scale, scale, scale);
      }
    }
  }
  return cv;
}

/* ─── Catalogo sprite ─── */

function makePlayer(dir) {
  /* 16x16 — cappotto blu, capelli biondi sotto al cappello */
  const palettes = {
    s: C.player_skin, b: C.player_body, h: C.player_hair,
    o: C.ink, w: '#ffffff', y: C.gold,
  };
  /* Forme semplificate per 4 direzioni */
  const ART = {
    down:`
....hhhhhh......
...hhhhhhhh.....
...hssssssh.....
...hssoosoh.....
....hsssssh.....
.....bbbbb......
....bbyybbb.....
....bbbbbbb.....
....bbbbbbb.....
.....bbbbb......
.....bb.bb......
.....bb.bb......
.....bb.bb......
.....oo.oo......
................
................`,
    up:`
....hhhhhh......
...hhhhhhhh.....
...hhhhhhhh.....
...hhhhhhhh.....
....hhhhhh......
.....bbbbb......
....bbbbbbb.....
....bbbbbbb.....
....bbbbbbb.....
.....bbbbb......
.....bb.bb......
.....bb.bb......
.....bb.bb......
.....oo.oo......
................
................`,
    right:`
.....hhhhhh.....
....hhhhhhhh....
....hssoosoh....
....hssssssh....
.....hssssh.....
......bbbbb.....
.....bbyybb.....
.....bbbbbb.....
.....bbbbbb.....
......bbbb......
......bb.b......
......bb.b......
......bb.b......
......oo.o......
................
................`,
    left:`
....hhhhhh......
...hhhhhhhh.....
...hosoosshh....
...hssssssh.....
....hsssssh.....
....bbbbb.......
....bbyybb......
....bbbbbb......
....bbbbbb......
.....bbbb.......
.....b.bb.......
.....b.bb.......
.....b.bb.......
.....o.oo.......
................
................`,
  };
  return drawPixelArt(ART[dir] || ART.down, palettes, 2);
}

function makeNpcOshus() {
  /* Vecchio saggio con barba bianca, tunica blu */
  const pal = { o: C.ink, s: C.player_skin, b: '#ffffff', t: '#306090', y: C.gold, w: '#e0e0e0' };
  const art = `
.....wwwwww.....
....wwwwwwww....
....wsoosoow....
....wssssssw....
....wsssssbw....
.....bbbbbb.....
....bbbbbbbb....
...tttttttttt...
...tttytttttt...
...tttytttttt...
...tttttttttt...
....tttttttt....
....tt....tt....
....tt....tt....
....oo....oo....
................`;
  return drawPixelArt(art, pal, 2);
}

function makeNpcLinebeck() {
  /* Capitano: cappello blu, giacca rossa */
  const pal = { o: C.ink, s: C.player_skin, b: C.blue, r: C.red, w: '#ffffff', y: C.gold };
  const art = `
....bbbbbbb.....
...bbbbbbbbb....
....ssssss......
....soossso.....
.....ssssss.....
......ssss......
.....rrrrrr.....
....rrrwwwrr....
....rrrwwrrr....
....rrrrrrrr....
....rrrrrrrr....
.....rrrrrr.....
.....bb..bb.....
.....bb..bb.....
.....oo..oo.....
................`;
  return drawPixelArt(art, pal, 2);
}

function makeNpcShopkeeper() {
  const pal = { o: C.ink, s: C.player_skin, g: '#3a8030', y: C.gold, w: '#ffffff' };
  const art = `
.....yyyyyy.....
....yyyyyyyy....
....ysssssy.....
....sosooso.....
.....ssssss.....
.....gggggg.....
....gggggggg....
....gggwgggg....
....ggwwwggg....
....gggwgggg....
....gggggggg....
.....gggggg.....
.....gg..gg.....
.....gg..gg.....
.....oo..oo.....
................`;
  return drawPixelArt(art, pal, 2);
}

function makeEnemyChuChu() {
  /* Slime gelatinoso azzurro */
  const pal = { o: C.ink, b: '#80c0e0', d: '#5090c0', w: '#ffffff' };
  const art = `
................
................
.....bbbb.......
....bbbbbb......
...bbbbbbbb.....
...bowbbbwob....
...bbbbbbbbb....
...bbbbbbbbb....
...dddddddddd...
....dddddddd....
.....dddddd.....
................
................
................
................
................`;
  return drawPixelArt(art, pal, 2);
}

function makeEnemyKeese() {
  /* Pipistrello */
  const pal = { o: C.ink, b: '#605070', w: '#ffffff', r: C.red };
  const art = `
................
................
....b......b....
...bb......bb...
..bbb..bb..bbb..
.bbbb.brrb.bbbb.
.bobwbbbbbwbob..
.bbbbbbbbbbbbb..
.bbbbbbbbbbbb...
..bbbbbbbbbb....
...bbbbbbbb.....
.....bbbb.......
................
................
................
................`;
  return drawPixelArt(art, pal, 2);
}

function makeEnemyPhantom() {
  /* Phantom: cavaliere armato, blu argento, occhi gialli */
  const pal = { o: C.ink, a: C.phantom_armor, d: '#606080', y: C.gold, w: '#ffffff' };
  const art = `
....aaaaaaaa....
...aaaaaaaaaa...
...aaaaaaaaaa...
...adyydydydya..
...adddddddddd..
...aaaaaaaaaa...
..aaaaaaaaaaaa..
..aaaaaaaaaaaa..
..addddddddddd..
..addaaaaaaadd..
..addaaaaaaadd..
..addaaaaaaadd..
...aaaaaaaaaa...
...aaaaaaaaaa...
...aa......aa...
...oo......oo...`;
  return drawPixelArt(art, pal, 2);
}

function makeBoat() {
  /* Vista dall'alto, prua a destra. */
  const pal = { o: C.ink, w: '#ffffff', t: C.trunk, b: C.blue, r: C.red, y: C.gold };
  const art = `
................
................
......t.........
......t.........
......t.........
.tttttttttttt...
.tbbbbbbbbbbt...
.twwwwwwwwwwt...
.twrwwwwwrwwt..t
.twwwwwwwwwwt.tt
.tbbbbbbbbbbtttt
.tttttttttttt...
................
................
................
................`;
  return drawPixelArt(art, pal, 2);
}

function makeItemSword() {
  const pal = { o: C.ink, w: '#e0e0e0', g: C.gold, t: C.trunk };
  const art = `
.......w........
.......w........
.......w........
......www.......
......www.......
......www.......
.....ggggg......
......ttt.......
......ttt.......
......ttt.......
......ggg.......
................
................
................
................
................`;
  return drawPixelArt(art, pal, 2);
}

function makeItemShield() {
  const pal = { o: C.ink, w: C.gold, b: C.blue, r: C.red };
  const art = `
.....wwwwww.....
....wwwwwwww....
....wbbbbbbw....
....wbbrrbbw....
....wbrrrrbw....
....wbrrrrbw....
....wbbrrbbw....
....wbbbbbbw....
....wwwwwwww....
.....wwwwww.....
......wwww......
................
................
................
................
................`;
  return drawPixelArt(art, pal, 2);
}

function makeItemBoomerang() {
  const pal = { o: C.ink, t: C.trunk, y: C.gold };
  const art = `
....yyyyy.......
...ytttttyy.....
..yttttttty.....
..yttyyttty.....
...yttttty......
....yttty.......
....yty.........
....y...........
................
................
................
................
................
................
................
................`;
  return drawPixelArt(art, pal, 2);
}

function makeItemBomb() {
  const pal = { o: C.ink, b: '#202020', g: '#404040', r: C.red, y: C.gold };
  const art = `
................
.......yy.......
......y.........
......y.........
.....bbbbbb.....
....bbbbbbbb....
...bbggbbbbbb...
...bggggbbbbb...
...bbggbbbbbb...
...bbbbbbbbbb...
....bbbbbbbb....
.....bbbbbb.....
................
................
................
................`;
  return drawPixelArt(art, pal, 2);
}

function makeItemBow() {
  const pal = { o: C.ink, t: C.trunk, w: '#e0e0e0' };
  const art = `
....tt..........
...t..t.........
..t....t........
.t......t.......
.t...wwwwwwww...
.t......t.......
..t....t........
...t..t.........
....tt..........
................
................
................
................
................
................
................`;
  return drawPixelArt(art, pal, 2);
}

function makeItemHeart() {
  const pal = { o: C.ink, r: C.red, p: '#ff8080', w: '#ffffff' };
  const art = `
................
....rr....rr....
...rrrr..rrrr...
..rwprr..rrprr..
..rrrrrrrrrrr...
..rrrrrrrrrrr...
..rrrrrrrrrrr...
...rrrrrrrrr....
....rrrrrrr.....
.....rrrrr......
......rrr.......
.......r........
................
................
................
................`;
  return drawPixelArt(art, pal, 2);
}

function makeItemRupee() {
  const pal = { o: C.ink, g: '#40c040', d: '#208020', w: '#ffffff' };
  const art = `
................
......gggg......
.....gggggg.....
....gggggggg....
....gwggggggg...
....gggggggg....
....gddggggdd...
....gdddggdgg...
.....gggggdg....
......dddd......
................
................
................
................
................
................`;
  return drawPixelArt(art, pal, 2);
}

function makeItemKey() {
  const pal = { o: C.ink, y: C.gold, d: C.gold_dk };
  const art = `
......yyyy......
.....yydyy......
.....yydyy......
.....yydyy......
......yyy.......
......yyy.......
......yyy.......
......yyy.......
......yyyy......
......yydyy.....
......yyyyy.....
......yyydy.....
......yyyyy.....
................
................
................`;
  return drawPixelArt(art, pal, 2);
}

function makeItemPotion() {
  const pal = { o: C.ink, g: '#40c040', t: C.trunk, w: '#ffffff' };
  const art = `
......tttt......
......t..t......
......t..t......
.....tggggt.....
....tggggggt....
....tggwgggt....
....tgggggwt....
....tggggggt....
....tggggggt....
.....tgggg......
.....tttttt.....
................
................
................
................
................`;
  return drawPixelArt(art, pal, 2);
}

function makeChest(opened) {
  const pal = { o: C.ink, t: C.trunk, d: '#4a3020', y: C.gold };
  const art = opened ? `
................
.tttttttttttt...
.t..........t...
.t..........t...
.tdddddddddddt..
.tdyydddddyydt..
.tdddddddddddt..
.tdddddyddddddt.
.tdyddddddydddt.
.tdddddddddddt..
.tdddddddddddt..
.ttttttttttttt..
................
................
................
................` : `
................
.tttttttttttt...
.tdddddddddddt..
.tdyydddddyydt..
.tdddddddddddt..
.tdddddyddddddt.
.tdyddddddydddt.
.tdddddddddddt..
.tdddddyydddddt.
.tdddyyyydddddt.
.tdddyyyydddddt.
.tdddddddddddt..
.ttttttttttttt..
................
................
................`;
  return drawPixelArt(art, pal, 2);
}

/* Lazy-load API */
const FACTORIES = {
  player_down:    () => makePlayer('down'),
  player_up:      () => makePlayer('up'),
  player_left:    () => makePlayer('left'),
  player_right:   () => makePlayer('right'),
  npc_oshus:      makeNpcOshus,
  npc_linebeck:   makeNpcLinebeck,
  npc_shopkeeper: makeNpcShopkeeper,
  enemy_chuchu:   makeEnemyChuChu,
  enemy_keese:    makeEnemyKeese,
  enemy_phantom:  makeEnemyPhantom,
  boat:           makeBoat,
  item_sword:     makeItemSword,
  item_shield:    makeItemShield,
  item_boomerang: makeItemBoomerang,
  item_bomb:      makeItemBomb,
  item_bow:       makeItemBow,
  item_heart:     makeItemHeart,
  item_rupee:     makeItemRupee,
  item_key:       makeItemKey,
  item_potion:    makeItemPotion,
  chest_closed:   () => makeChest(false),
  chest_open:     () => makeChest(true),
};

export function getSprite(name) {
  if (cache.has(name)) return cache.get(name);
  const f = FACTORIES[name];
  if (!f) return null;
  const s = f();
  cache.set(name, s);
  return s;
}

/** Disegna sprite scalato (no smoothing, pixel art crisp). */
export function drawSprite(ctx, name, dx, dy, dw, dh) {
  const s = getSprite(name);
  if (!s) return;
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(s, dx, dy, dw, dh);
}
